# Generated by Django 4.2 on 2026-01-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=255),
        ),
    ]
